/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/female_body.gltf')
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.mixamorigHips} />
      <skinnedMesh name="Bra" geometry={nodes.Bra.geometry} material={materials['5_meshes_Merge.003']} skeleton={nodes.Bra.skeleton} />
      <skinnedMesh name="CC_Base_Body" geometry={nodes.CC_Base_Body.geometry} material={materials['5_meshes_Merge.003']} skeleton={nodes.CC_Base_Body.skeleton} />
      <skinnedMesh name="CC_Base_Eye" geometry={nodes.CC_Base_Eye.geometry} material={materials['5_meshes_Merge.003']} skeleton={nodes.CC_Base_Eye.skeleton} />
      <skinnedMesh name="Underwear_Bottoms" geometry={nodes.Underwear_Bottoms.geometry} material={materials['5_meshes_Merge.003']} skeleton={nodes.Underwear_Bottoms.skeleton} />
    </group>
  )
}

useGLTF.preload('/female_body.gltf')
