/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/gym.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh name="Plane" geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[4.61, 7.9, -17.99]} />
      <group name="wall_glass" position={[4.61, 7.9, -17.99]}>
        <mesh name="wall_gass" geometry={nodes.wall_gass.geometry} material={materials.mtl_glass} />
        <mesh name="wall_gass_1" geometry={nodes.wall_gass_1.geometry} material={materials.mtl_glass} />
      </group>
      <mesh name="wall_metal" geometry={nodes.wall_metal.geometry} material={materials.mtl_wall_metal} position={[4.61, 7.9, -17.99]} />
      <mesh name="wall_mirror" geometry={nodes.wall_mirror.geometry} material={materials.mtl_wall_mirror} position={[4.61, 7.9, -17.99]} />
      <mesh name="floor" geometry={nodes.floor.geometry} material={nodes.floor.material} position={[4.61, 7.9, -17.99]} />
      <mesh name="wall_intr" geometry={nodes.wall_intr.geometry} material={nodes.wall_intr.material} position={[4.61, 7.9, -17.99]} />
    </group>
  )
}

useGLTF.preload('/gym.gltf')
